# Generated by Django 5.1.1 on 2025-02-09 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("subscriber", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                related_name="is_followed_by",
                through="subscriber.UserFollows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
