# Generated by Django 5.1.1 on 2025-04-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_userfollows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustom",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
